import fs from "fs";
import path from "path";
import csv from "csv-parser";
import prisma from "../config/db";
import { ShippingType } from "../generated/prisma/client";

// Función mágica para generar el código alfanumérico
const generateUniqueCode = (
  name: string,
  existingCodes: Set<string>,
): string => {
  // 1. Quitamos espacios y caracteres especiales, y pasamos a mayúsculas
  const cleanName = name.replace(/[^a-zA-Z0-9]/g, "").toUpperCase();

  // 2. Tomamos las primeras 3 letras (si el nombre es muy corto, rellenamos con 'X')
  let prefix = cleanName.substring(0, 3);
  if (prefix.length < 3) {
    prefix = prefix.padEnd(3, "X");
  }

  // 3. Buscamos el número disponible
  let counter = 1;
  let newCode = `${prefix}${counter.toString().padStart(3, "0")}`;

  while (existingCodes.has(newCode)) {
    counter++;
    newCode = `${prefix}${counter.toString().padStart(3, "0")}`;
  }

  // 4. Lo registramos en el Set para que no se repita en la misma ejecución
  existingCodes.add(newCode);

  return newCode;
};

const importClients = async () => {
  const results: any[] = [];
  const filePath = path.join(__dirname, "../../data/clientes2.csv");

  console.log("⏳ Precargando relaciones y códigos existentes...");

  const categories = await prisma.category.findMany();
  const cities = await prisma.city.findMany();
  const carriers = await prisma.carrier.findMany();

  // Traemos TODOS los códigos que ya están guardados en PostgreSQL
  const existingClients = await prisma.client.findMany({
    select: { code: true },
  });

  const categoryMap = new Map(
    categories.map((c) => [c.name.trim().toLowerCase(), c.id]),
  );
  const cityMap = new Map(
    cities.map((c) => [c.name.trim().toLowerCase(), c.id]),
  );
  const carrierMap = new Map(
    carriers.map((c) => [c.name.trim().toLowerCase(), c.id]),
  );

  // Creamos el Set con los códigos existentes para búsquedas ultra rápidas
  const existingCodes = new Set(existingClients.map((c) => c.code));

  console.log("⏳ Leyendo archivo CSV de clientes...");

  fs.createReadStream(filePath)
    .pipe(
      csv({
        mapHeaders: ({ header }) =>
          header.trim().replace(/^[\uFEFF\xEF\xBB\xBF]+/, ""),
      }),
    )
    .on("data", (data) => results.push(data))
    .on("end", async () => {
      try {
        const clientsToInsert: any[] = [];
        let autoGeneratedCount = 0;

        for (const row of results) {
          const name = row["inau"]?.trim() || row["Nombre de Busqueda"]?.trim();
          if (!name) continue;

          // Si el CSV trae un código, lo usamos. Si no, lo generamos con tu lógica.
          let code = row["Codigo"]?.trim();
          if (!code) {
            code = generateUniqueCode(name, existingCodes);
            autoGeneratedCount++;
          } else {
            // Si el código viene del CSV, lo agregamos al Set para registrar que ya está en uso
            existingCodes.add(code);
          }

          const categoryName = row["Rubro"]?.trim().toLowerCase();
          const categoryId = categoryName
            ? categoryMap.get(categoryName)
            : null;

          const cityName = row["Localidad"]?.trim().toLowerCase();
          const cityId = cityName ? cityMap.get(cityName) : null;

          const carrierName = row["Comisionista"]?.trim().toLowerCase();
          const carrierId = carrierName ? carrierMap.get(carrierName) : null;

          let shippingType: ShippingType | null = null;
          const rawShipping = row["Tipo Envio"]?.trim().toUpperCase();
          if (
            rawShipping === "RGE" ||
            rawShipping === "RETIRA" ||
            rawShipping === "CORREO" ||
            rawShipping === "EXPRESO"
          ) {
            shippingType = rawShipping as ShippingType;
          }

          let discountVal = 0;
          const rawDiscount = row["Descuento"];
          if (rawDiscount && rawDiscount.trim() !== "") {
            const parsed = parseFloat(
              rawDiscount.replace("%", "").replace(",", "."),
            );
            if (!isNaN(parsed)) discountVal = parsed / 100;
          }

          clientsToInsert.push({
            code: code,
            name: name,
            searchName: row["Nombre de Busqueda"]?.trim() || null,
            address: row["Direccion"]?.trim() || null,
            phone: row["Telefono"]?.trim() || null,
            email: row["Mail"]?.trim() || null,
            altPhone: row["Otro Telefono"]?.trim() || null,
            taxCategory: row["Condicion IVA"]?.trim() || null,
            cuitDni: row["CUIT / DNI"]?.trim() || null,
            discount: discountVal,
            shippingType: shippingType,
            paymentTerms: row["Como Paga"]?.trim() || null,
            notes: row["Observaciones 1"]?.trim() || null,
            userMercadoPago: row["Usuario Mercado Pago"]?.trim() || null,
            categoryId: categoryId || null,
            cityId: cityId || null,
            carrierId: carrierId || null,
          });
        }

        console.log(
          `📦 Se procesaron ${clientsToInsert.length} clientes. Insertando en la base de datos...`,
        );

        const insertResult = await prisma.client.createMany({
          data: clientsToInsert,
          skipDuplicates: true,
        });

        console.log(
          `✅ ¡Éxito! Se importaron ${insertResult.count} clientes nuevos.`,
        );
        if (autoGeneratedCount > 0) {
          console.log(
            `✨ Se autogeneraron ${autoGeneratedCount} códigos inteligentes (ej. ABC001) para clientes sin código.`,
          );
        }
      } catch (error) {
        console.error("❌ Error importando clientes:", error);
      } finally {
        await prisma.$disconnect();
      }
    });
};

importClients();
